# Generated by Django 5.0.2 on 2024-02-19 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='categoriaId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='flix.categoria'),
        ),
    ]
